apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-secret-store-chatbot
spec:
  provider:
    vault:
      auth:
        kubernetes:
          mountPath: kubernetes
          role: rhdh-role
          secretRef:
            key: token
            name: vault-auth-secret
            namespace: default
          serviceAccountRef:
            name: vault-auth
            namespace: default
      path: secrets
      server: http://vault.vault:8200
      version: v2
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-hftoken
spec:
  secretStoreRef:
    name: vault-secret-store-chatbot
    kind: ClusterSecretStore
  target:
    name: huggingface-secret
  data:
  - secretKey: HF_TOKEN
    remoteRef:
      key: secrets/ai-kickstart
      property: hf_token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: llama-stack-env-from-vault
spec:
  secretStoreRef:
    name: vault-secret-store-chatbot
    kind: ClusterSecretStore
  target:
    name: llama-stack-env # Exact name the chart expects
  data:
    - secretKey: TAVILY_SEARCH_API_KEY
      remoteRef:
        key: secrets/tavily # Vault path
        property: tavily_api_key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tavily-secret-from-vault
spec:
  secretStoreRef:
    name: vault-secret-store-chatbot
    kind: ClusterSecretStore
  target:
    name: tavily-secret
  data:
    - secretKey: TAVILY_API_KEY
      remoteRef:
        key: secrets/tavily
        property: tavily_api_key
