---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.name }}-rag-ui
  namespace: ${{ values.argonamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ${{ values.name }}-bootstrap
  source:
    repoURL: ${{values.repoURL}}
    targetRevision: HEAD
    path: ./helm/rag
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: global.models.${{ values.llm }}.enabled
          value: "true"
        - name: global.models.${{ values.safety }}.enabled
          value: "${{ values.enable_safety }}"
        - name: mcp-servers.weather.enabled
          value: "true"
        - name: mcp-servers.weather.deploymentMode
          value: "deployment"
        - name: mcp-servers.weather.image.repository
          value: "quay.io/rh-ai-quickstart/mcp-weather"
        - name: mcp-servers.weather.image.tag
          value: ""
        - name: mcp-servers.weather.transport
          value: "sse"
         - name: mcp-servers.weather.targetPort
          value: "8000"
        #- name: mcp-servers.mcp-servers.weather.persistence.enabled
          #value: "true"
        #- name: mcp-servers.mcp-servers.weather.persistence.accessMode
          #value: "ReadWriteOnce"
        #- name: mcp-servers.mcp-servers.weather.persistence.size
          #value: "5Gi"
        - name: llm-service.secret.enabled
          value: "false"
        - name: ingestion-pipeline.defaultPipeline.enabled
          value: "true"
        - name: ingestion-pipeline.enableSigning
          value: "${{ values.enable_db_signing }}"
        - name: mcp-servers.oracle-sqlcl.enabled
          value: "false"
        #if using vault, use the following
        #- name: global.mcp-servers.weather.envSecrets.TAVILY_API_KEY.name
          #value: "tavily-secret"
        #- name: global.mcp-servers.weather.envSecrets.TAVILY_API_KEY.key
          #value: "TAVILY_API_KEY"
        #uncomment the following if vault and external secrets are not used
        #- name: global.mcp-servers.weather.env.TAVILY_API_KEY
          #value: "<TAVILY_API_KEY>"
        - name: llama-stack.secrets.TAVILY_SEARCH_API_KEY
          value: "tavily_api_key"
        #--- 
        - name: llama-stack.mcp-servers.weather.enabled
          value: "true"
        - name: llama-stack.mcp-servers.weather.uri
          value: "http://mcp-weather.${{ values.namespace }}.svc.cluster.local:8000/sse"
      values: |
        llama-stack:
          secrets: {}
    
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{ values.namespace }}
  ignoreDifferences:
    - group: "*"
      jqPathExpressions:
        - '.imagePullSecrets[] | select(.name | contains("-dockercfg-"))'
      kind: ServiceAccount
    - group: kubeflow.org
      jqPathExpressions:
        - '.spec.template.spec.containers[] | select(.name == "oauth-proxy")'
        - '.spec.template.spec.volumes[] | select(.name | IN("trusted-ca", "oauth-config", "tls-certificates"))'
        - '.spec.template.spec.containers[] | select(.name != "oauth-proxy").env[] | select(.name | IN("PIP_CERT", "REQUESTS_CA_BUNDLE", "SSL_CERT_FILE", "PIPELINES_SSL_SA_CERTS", "GIT_SSL_CAINFO"))'
        - '.spec.template.spec.containers[] | select(.name != "oauth-proxy").volumeMounts[] | select(.name == "trusted-ca")'
      kind: Notebook
    - group: route.openshift.io
      jsonPointers:
        - /metadata/annotations/openshift.io~1host.generated
        - /spec/alternateBackends
      kind: Route
    - group: batch
      jsonPointers:
        - /spec/selector
        - /spec/completionMode
      kind: Job
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: -1
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 2m # the maximum amount of time allowed for the backoff strategy
